BOARD_SIZE = 9
NUM_START_WALLS = 10

WHITE_PAWN_SYMBOL = '\u25CD'
BLACK_PAWN_SYMBOL = '\u25CF'
HORIZONTAL_WALL_SYMBOL = '\u2501'
VERTICAL_WALL_SYMBOL = '\u2503'
SQUARE_SYMBOL = '\u25A2'
EMPTY_SYMBOL = ' '
